name = "worker-today-in-history"
main = "src/index.ts"
compatibility_date = "2022-06-03"

[vars]
TWITTER_BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAAHcidQEAAAAAQ56JjrW6jhS2A7IgytXox022BHg%3DI6KVdOPBkTukQ7iNOXYLB0TEACpwUBrNP8GY1H63D6mk8zOsWB"
PAGES_URL="http://localhost:3000"
